### ISSUE TITLE
kubectl command line API changed, causing vagrant up to fail

### ISSUE THREAD

**Issue by irth** [sokoow/kube-desktop#2]
I'm using Vagrant 2.2.3 on a mostly up-to-date Arch Linux install.

**`vagrant-up` output**

    (...)
    kube1: serviceaccount/traefik-ingress-controller created
    kube1: daemonset.extensions/traefik-ingress-controller created
    kube1: service/traefik-ingress-service created
    kube1: 
    kube1: Running inside Vagrant
    kube1: Error: unknown flag: --apiserver-advertise-address
    kube1: Usage:
    kube1: 
    kube1: Flags:
    kube1:   -h, --help   help for phase
    kube1: 
    kube1: Global Flags:
    kube1:       --log-file string   If non-empty, use this log file
    kube1:       --rootfs string     [EXPERIMENTAL] The path to the 'real' host root filesystem.
    kube1:       --skip-headers      If true, avoid header prefixes in the log messages
    kube1:   -v, --v Level           log level for V logs
    kube1: 
    kube1: error: unknown flag: --apiserver-advertise-address

**Location of the erroneous line:**
```
$ ag apiserver-advertise-address
install-kubeadm.sh
87:sudo kubeadm alpha phase certs all --apiserver-advertise-address=0.0.0.0 --apiserver-cert-extra-sans=127.0.0.1
```

**`kubeadm` version:**
```
vagrant@kube-desktop:~$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sokoow** [comment]
fixed in https://github.com/sokoow/kube-desktop/commit/6cb1b6884ca2392abd4c869f9da84a828b16183e , check it on your side pls

kubeadm changed its command line args in meanwhile

**Comment by irth** [comment]
Works now, thanks.
